import ar.com.elegantsoft.ftbmods.*

class BootStrap {

	def init = { servletContext ->
		environments {
			test { vanillaItems() }
			development {
			}
		}
	}

	def destroy = {
	}

	def vanillaItems() {
		Pack pack
		Modif amod
		Set<Item> items = new HashSet<Item>() 

		new Pack(packName:'Feed The Beast', packVersion:'1.0', packCreator: 'The FTB Team')
			.addToPackMods(new Modif(modName:'vanilla', modVersion: '1.5.0', modCreator: 'Mojang', 
					modUrl:'http://www.minecraft.net')
				.addToModItems(new Item(priId:'0', name:'Air', pic:'air'))
				.addToModItems(new Item(priId:'1', name:'Stone', pic:'stone'))
				.addToModItems(new Item(priId:'2', name:'Grass Block', pic:'grass_block'))
				.addToModItems(new Item(priId:'3', name:'Dirt', pic:'dirt'))
				.addToModItems(new Item(priId:'4', name:'Cobblestone', pic:'cobblestone'))
				.addToModItems(new Item(priId:'5', name:'Oak Wooden Plank', pic:'oak_wood_plank'))
				.addToModItems(new Item(priId:'5', secId:'1', name:'Birch Wooden Plank', pic:'birch_wood_plank'))
				.addToModItems(new Item(priId:'5', secId:'2', name:'Spruce Wooden Plank', pic:'spruce_wood_plank'))
				.addToModItems(new Item(priId:'5', secId:'3', name:'Jungle Wooden Plank', pic:'jungle_wood_plank'))
				.addToModItems(new Item(priId:'6', secId:'0', name:'Oak Sapling', pic:'oak_sapling'))
				.addToModItems(new Item(priId:'6', secId:'1', name:'Birch Sapling', pic:'birch_sapling'))
				.addToModItems(new Item(priId:'6', secId:'2', name:'Pine Sapling', pic:'pine_sapling'))
				.addToModItems(new Item(priId:'6', secId:'3', name:'Jungle Sapling', pic:'jungle_sapling'))
				.addToModItems(new Item(priId:'7', name:'Bedrock', pic:'bedrock'))
				.addToModItems(new Item(priId:'8', name:'Water', pic:'water'))
				.addToModItems(new Item(priId:'9', name:'Stationary water', pic:'stationary_water'))
				.addToModItems(new Item(priId:'10', name:'Lava', pic:'lava'))
				.addToModItems(new Item(priId:'11', name:'Stationary lava', pic:'stationary_lava'))
				.addToModItems(new Item(priId:'12', name:'Sand', pic:'sand'))
				.addToModItems(new Item(priId:'13', name:'Gravel', pic:'gravel'))
				.addToModItems(new Item(priId:'14', name:'Gold Ore', pic:'gold_ore'))
				.addToModItems(new Item(priId:'15', name:'Iron Ore', pic:'iron_ore'))
				.addToModItems(new Item(priId:'16', name:'Coal Ore', pic:'coal_ore'))
				.addToModItems(new Item(priId:'17', secId:'0', name:'Oak Wood', pic:'oak_wood'))
				.addToModItems(new Item(priId:'17', secId:'1', name:'Spruce Wood', pic:'spruce_wood'))
				.addToModItems(new Item(priId:'17', secId:'2', name:'Birch Wood', pic:'birch_wood'))
				.addToModItems(new Item(priId:'17', secId:'3', name:'Jungle Wood', pic:'jungle_wood'))
				.addToModItems(new Item(priId:'18', secId:'0', name:'Oak Leaves', pic:'oak_leaves'))
				.addToModItems(new Item(priId:'18', secId:'1', name:'Spruce Leaves', pic:'spruce_leaves'))
				.addToModItems(new Item(priId:'18', secId:'2', name:'Birch Leaves', pic:'birch_leaves'))
				.addToModItems(new Item(priId:'18', secId:'3', name:'Jungle Leaves', pic:'jungle_leaves'))
				.addToModItems(new Item(priId:'19', name:'Sponge', pic:'sponge'))
				.addToModItems(new Item(priId:'20', name:'Glass', pic:'glass'))
				.addToModItems(new Item(priId:'21', name:'Lapis Lazuli Ore', pic:'lapis_lazuli_ore'))
				.addToModItems(new Item(priId:'22', name:'Lapis Lazuli Block', pic:'lapis_lazuli_block'))
				.addToModItems(new Item(priId:'23', name:'Dispenser', pic:'dispenser'))
				.addToModItems(new Item(priId:'24', name:'Sandstone', pic:'sandstone'))
				.addToModItems(new Item(priId:'24', secId:'1', name:'Chiseled Sandstone', pic:'chiseled_sandstone'))
				.addToModItems(new Item(priId:'24', secId:'2', name:'Smooth Sandstone', pic:'smooth_sandstone'))
				.addToModItems(new Item(priId:'25', name:'Note Block', pic:'note_block'))
				.addToModItems(new Item(priId:'26', name:'Bed (Block)', pic:'bed_block'))
				.addToModItems(new Item(priId:'27', name:'Powered Rail', pic:'powered_rail'))
				.addToModItems(new Item(priId:'28', name:'Detector Rail', pic:'detector_rail'))
				.addToModItems(new Item(priId:'29', name:'Sticky Piston', pic:'sticky_piston'))
				.addToModItems(new Item(priId:'30', name:'Cobweb', pic:'cobweb'))
				.addToModItems(new Item(priId:'31', name:'Tall Grass', pic:'tall_grass'))
				.addToModItems(new Item(priId:'31', secId:'1', name:'Tall Grass (Dead Shrub)', pic:'tall_grass_shrub'))
				.addToModItems(new Item(priId:'31', secId:'2', name:'Tall Grass (Fern)', pic:'tall_grass_fern'))
				.addToModItems(new Item(priId:'32', name:'Dead Bush', pic:'dead_bush'))
				.addToModItems(new Item(priId:'33', name:'Piston', pic:'piston'))
				.addToModItems(new Item(priId:'34', name:'Piston Extension', pic:'piston_extension'))
				.addToModItems(new Item(priId:'35', secId:'0', name:'Wool', pic:'wool'))
				.addToModItems(new Item(priId:'35', secId:'1', name:'Orange Wool', pic:'orange_wool'))
				.addToModItems(new Item(priId:'35', secId:'2', name:'Magenta Wool', pic:'magenta_wool'))
				.addToModItems(new Item(priId:'35', secId:'3', name:'Light Blue Wool', pic:'light_blue_wool'))
				.addToModItems(new Item(priId:'35', secId:'4', name:'Yellow Wool', pic:'yellow_wool'))
				.addToModItems(new Item(priId:'35', secId:'5', name:'Lime Wool', pic:'lime_wool'))
				.addToModItems(new Item(priId:'35', secId:'6', name:'Pink Wool', pic:'pink_wool'))
				.addToModItems(new Item(priId:'35', secId:'7', name:'Gray Wool', pic:'gray_wool'))
				.addToModItems(new Item(priId:'35', secId:'8', name:'Light Gray Wool', pic:'light_gray_wool'))
				.addToModItems(new Item(priId:'35', secId:'9', name:'Cyan Wool', pic:'cyan_wool'))
				.addToModItems(new Item(priId:'35', secId:'10', name:'Purple Wool', pic:'purple_wool'))
				.addToModItems(new Item(priId:'35', secId:'11', name:'Blue Wool', pic:'blue_wool'))
				.addToModItems(new Item(priId:'35', secId:'12', name:'Brown Wool', pic:'brown_wool'))
				.addToModItems(new Item(priId:'35', secId:'13', name:'Green Wool', pic:'green_wool'))
				.addToModItems(new Item(priId:'35', secId:'14', name:'Red Wool', pic:'red_wool'))
				.addToModItems(new Item(priId:'35', secId:'15', name:'Black Wool', pic:'black_wool'))
				.addToModItems(new Item(priId:'36', name:'Block moved by Piston', pic:'block_moved_by_piston'))
				.addToModItems(new Item(priId:'37', name:'Dandelion', pic:'dandelion'))
				.addToModItems(new Item(priId:'38', name:'Rose', pic:'rose'))
				.addToModItems(new Item(priId:'39', name:'Brown Mushroom', pic:'brown_mushroom'))
				.addToModItems(new Item(priId:'40', name:'Red Mushroom', pic:'red_mushroom'))
				.addToModItems(new Item(priId:'41', name:'Block of Gold', pic:'block_of_gold'))
				.addToModItems(new Item(priId:'42', name:'Block of Iron', pic:'block_of_iron'))
				.addToModItems(new Item(priId:'43', secId:'0', name:'Double Stone Slabs', pic:'double_stone_slabs'))
				.addToModItems(new Item(priId:'43', secId:'1', name:'Double Sandstone Slabs', pic:'double_sandstone_slabs'))
				.addToModItems(new Item(priId:'43', secId:'2', name:'Double Wooden Slabs', pic:'double_woodenslabs'))
				.addToModItems(new Item(priId:'43', secId:'3', name:'Double Cobblestone Slabs', pic:'double_cobblestone_slabs'))
				.addToModItems(new Item(priId:'43', secId:'4', name:'Double Brick Slabs', pic:'double_brick_slabs'))
				.addToModItems(new Item(priId:'43', secId:'5', name:'Double Stone Brick Slabs', pic:'double_stone_brick_slabs'))
				.addToModItems(new Item(priId:'43', secId:'6', name:'Double Nether Brick Slabs', pic:'double_nether_brick_slabs'))
				.addToModItems(new Item(priId:'43', secId:'7', name:'Double Quartz Brick Slabs', pic:'double_quartz_brick_slabs'))
				.addToModItems(new Item(priId:'44', secId:'0', name:'Stone Slabs', pic:'stone_slabs'))
				.addToModItems(new Item(priId:'44', secId:'1', name:'Sandstone Slabs', pic:'sandstone_slabs'))
				.addToModItems(new Item(priId:'44', secId:'2', name:'Wooden Slabs', pic:'woodenslabs'))
				.addToModItems(new Item(priId:'44', secId:'3', name:'Cobblestone Slabs', pic:'cobblestone_slabs'))
				.addToModItems(new Item(priId:'44', secId:'4', name:'Brick Slabs', pic:'brick_slabs'))
				.addToModItems(new Item(priId:'44', secId:'5', name:'Stone Brick Slabs', pic:'_stone_brick_slabs'))
				.addToModItems(new Item(priId:'44', secId:'6', name:'Nether Brick Slabs', pic:'nether_brick_slabs'))
				.addToModItems(new Item(priId:'44', secId:'7', name:'Quartz Brick Slabs', pic:'quartz_brick_slabs'))
				.addToModItems(new Item(priId:'45', name:'Bricks', pic:'bricks'))
				.addToModItems(new Item(priId:'46', name:'TNT', pic:'tnt'))
				.addToModItems(new Item(priId:'47', name:'Bookshelf', pic:'bookshelf'))
				.addToModItems(new Item(priId:'48', name:'Moss Stone', pic:'moss_stone'))
				.addToModItems(new Item(priId:'49', name:'Obsidian', pic:'obsidian'))
				.addToModItems(new Item(priId:'50', name:'Torch', pic:'torch'))
				.addToModItems(new Item(priId:'51', name:'Fire', pic:'fire'))
				.addToModItems(new Item(priId:'52', name:'Monster Spawner', pic:'monster_spawner'))
				.addToModItems(new Item(priId:'53', name:'Oak Wood Stairs', pic:'oak_wood_stairs'))
				.addToModItems(new Item(priId:'54', name:'Chest', pic:'vhest'))
				.addToModItems(new Item(priId:'55', name:'Redstone Wire', pic:'redstone_wire'))
				.addToModItems(new Item(priId:'56', name:'Diamond Ore', pic:'diamond_ore'))
				.addToModItems(new Item(priId:'57', name:'Block of Diamond', pic:'block_of_diamond'))
				.addToModItems(new Item(priId:'58', name:'Crafting Table', pic:'crafting_table'))
				.addToModItems(new Item(priId:'59', name:'Wheat Crop', pic:'wheat_crop'))
				.addToModItems(new Item(priId:'60', name:'Farmland', pic:'farmland'))
				.addToModItems(new Item(priId:'61', name:'Furnace', pic:'furnace'))
				.addToModItems(new Item(priId:'62', name:'Burning Furnace', pic:'burning_furnace'))
				.addToModItems(new Item(priId:'63', name:'Sign Post', pic:'sign_post'))
				.addToModItems(new Item(priId:'64', name:'Wooden Door', pic:'wooden_door'))
				.addToModItems(new Item(priId:'65', name:'Ladders', pic:'ladders'))
				.addToModItems(new Item(priId:'66', name:'Rails', pic:'rails'))
				.addToModItems(new Item(priId:'67', name:'Cobblestone Stairs', pic:'cobblestone_stairs'))
				.addToModItems(new Item(priId:'68', name:'Wall Sign', pic:'wall_sign'))
				.addToModItems(new Item(priId:'69', name:'Lever', pic:'lever'))
				.addToModItems(new Item(priId:'70', name:'Stone Pressure Plate', pic:'stone_pressure_plate'))
				.addToModItems(new Item(priId:'71', name:'Iron Door', pic:'iron_door'))
				.addToModItems(new Item(priId:'72', name:'Wooden Pressure Plate', pic:'wooden_pressure_plate'))
				.addToModItems(new Item(priId:'73', name:'Redstone Ore', pic:'redstone_ore'))
				.addToModItems(new Item(priId:'74', name:'Glowing Redstone Ore', pic:'glowing_redstone_ore'))
				.addToModItems(new Item(priId:'75', name:'Redstone Torch (inactive)', pic:'redstone_torch_i'))
				.addToModItems(new Item(priId:'76', name:'Redstone Torch (active)', pic:'redstone_torch_a'))
				.addToModItems(new Item(priId:'77', name:'Stone Button', pic:'stone_button'))
				.addToModItems(new Item(priId:'78', name:'Snow', pic:'snow'))
				.addToModItems(new Item(priId:'79', name:'Ice', pic:'ice'))
				.addToModItems(new Item(priId:'80', name:'Snow Block', pic:'snow_block'))
				.addToModItems(new Item(priId:'81', name:'Cactus', pic:'cactus'))
				.addToModItems(new Item(priId:'82', name:'Clay Block', pic:'clay_block'))
				.addToModItems(new Item(priId:'83', name:'Sugar Cane', pic:'sugar_cane'))
				.addToModItems(new Item(priId:'84', name:'Jukebox', pic:'jukebox'))
				.addToModItems(new Item(priId:'85', name:'Fence', pic:'fence'))
				.addToModItems(new Item(priId:'86', name:'Pumpkin', pic:'pumpkin'))
				.addToModItems(new Item(priId:'87', name:'Netherrack', pic:'netherrack'))
				.addToModItems(new Item(priId:'88', name:'Soul Sand', pic:'soul_sand'))
				.addToModItems(new Item(priId:'89', name:'Glowstone Block', pic:'glowstone_block'))
				.addToModItems(new Item(priId:'90', name:'Nether Portal', pic:'nether_portal'))
				.addToModItems(new Item(priId:'91', name:'Jack \'o\' Lantern', pic:'jack_o_lantern'))
				.addToModItems(new Item(priId:'92', name:'Cake Block', pic:'cake_block'))
				.addToModItems(new Item(priId:'93', name:'Redstone Repeater (inactive)', pic:'redstone_repeater_i'))
				.addToModItems(new Item(priId:'94', name:'Redstone Repeater (active)', pic:'redstone_repeater_a'))
				.addToModItems(new Item(priId:'95', name:'Locked Chest', pic:'locked_chest'))
				.addToModItems(new Item(priId:'96', name:'Trapdoor', pic:'trapdoor'))
				.addToModItems(new Item(priId:'97', secId:'0', name:'Silverfish Stone', pic:'silverfish_stone'))
				.addToModItems(new Item(priId:'97', secId:'1', name:'Silverfish Cobblestone', pic:'silverfish_cobblestone'))
				.addToModItems(new Item(priId:'97', secId:'2', name:'Silverfish Stone Brick', pic:'silverfish_stone_brick'))
				.addToModItems(new Item(priId:'98', secId:'0', name:'Stone Bricks', pic:'stone_bricks'))
				.addToModItems(new Item(priId:'98', secId:'1', name:'Mossy Stone Bricks', pic:'mossy_stone_bricks'))
				.addToModItems(new Item(priId:'98', secId:'2', name:'Cracked Stone Bricks', pic:'cracked_stone_bricks'))
				.addToModItems(new Item(priId:'98', secId:'3', name:'Chiseled Stone Bricks', pic:'chiseled_stone_bricks'))
				.addToModItems(new Item(priId:'99', name:'Huge Brown Mushroom', pic:'huge_brown_mushroom'))
				.addToModItems(new Item(priId:'100', name:'Huge Red Mushroom', pic:'huge_red_mushroom'))
				.addToModItems(new Item(priId:'101', name:'Iron Bars', pic:'iron_bars'))
				.addToModItems(new Item(priId:'102', name:'Glass Pane', pic:'glass_pane'))
				.addToModItems(new Item(priId:'103', name:'Melon', pic:'melon'))
				.addToModItems(new Item(priId:'104', name:'Pumpkin Stem', pic:'pumpkin_stem'))
				.addToModItems(new Item(priId:'105', name:'Melon Stem', pic:'melon_stem'))
				.addToModItems(new Item(priId:'106', name:'Vines', pic:'vines'))
				.addToModItems(new Item(priId:'107', name:'Fence Gate', pic:'fence_gate'))
				.addToModItems(new Item(priId:'108', name:'Brick Stairs', pic:'brick_stairs'))
				.addToModItems(new Item(priId:'109', name:'Stone Brick Stairs', pic:'stone_brick_stairs'))
				.addToModItems(new Item(priId:'110', name:'Mycelium', pic:'mycelium'))
				.addToModItems(new Item(priId:'111', name:'Lily Pad', pic:'lily_pad'))
				.addToModItems(new Item(priId:'112', name:'Nether Brick', pic:'nether_brick'))
				.addToModItems(new Item(priId:'113', name:'Nether Brick Fence', pic:'nether_brick_fence'))
				.addToModItems(new Item(priId:'114', name:'Nether Brick Stairs', pic:'nether_brick_stairs'))
				.addToModItems(new Item(priId:'115', name:'Nether Wart', pic:'nether_wart'))
				.addToModItems(new Item(priId:'116', name:'Enchantment Table', pic:'enchantment_table'))
				.addToModItems(new Item(priId:'117', name:'Brewing Stand', pic:'brewing_stand'))
				.addToModItems(new Item(priId:'118', name:'Cauldron', pic:'cauldron'))
				.addToModItems(new Item(priId:'119', name:'End Portal', pic:'end_portal'))
				.addToModItems(new Item(priId:'120', name:'End Portal Frame', pic:'end_portal_frame'))
				.addToModItems(new Item(priId:'121', name:'End Stone', pic:'end_stone'))
				.addToModItems(new Item(priId:'122', name:'Dragon Egg', pic:'dragon_egg'))
				.addToModItems(new Item(priId:'123', name:'Redstone Lamp (inactive)', pic:'redstone_lamp_i'))
				.addToModItems(new Item(priId:'124', name:'Redstone Lamp (active)', pic:'redstone_lamp_a'))
				.addToModItems(new Item(priId:'125', secId:'0', name:'Oak Wood Double Slab', pic:'oak_wood_double_slab'))
				.addToModItems(new Item(priId:'125', secId:'1', name:'Sptuce Wood Double Slab', pic:'spruce_wood_double_slab'))
				.addToModItems(new Item(priId:'125', secId:'2', name:'Birch Wood Double Slab', pic:'birch_wood_double_slab'))
				.addToModItems(new Item(priId:'125', secId:'3', name:'Jungle Wood Double Slab', pic:'jungle_wood_double_slab'))
				.addToModItems(new Item(priId:'126', secId:'0', name:'Oak Wood Slab', pic:'oak_wood_slab'))
				.addToModItems(new Item(priId:'126', secId:'1', name:'Sptuce Wood Slab', pic:'spruce_wood_slab'))
				.addToModItems(new Item(priId:'126', secId:'2', name:'Birch Wood Slab', pic:'birch_wood_slab'))
				.addToModItems(new Item(priId:'126', secId:'3', name:'Jungle Wood Slab', pic:'jungle_wood_slab'))
				.addToModItems(new Item(priId:'127', name:'Cocoa Pod', pic:'cocoa_pod'))
				.addToModItems(new Item(priId:'128', name:'Sandstone Stairs', pic:'sandstone_stairs'))
				.addToModItems(new Item(priId:'129', name:'Emerald Ore', pic:'emerald_ore'))
				.addToModItems(new Item(priId:'130', name:'Ender Chest', pic:'ender_chest'))
				.addToModItems(new Item(priId:'131', name:'Tripwire Hook', pic:'tripwire_hook'))
				.addToModItems(new Item(priId:'132', name:'Tripwire', pic:'tripwire'))
				.addToModItems(new Item(priId:'133', name:'Block of Emerald', pic:'block_of_emerald'))
				.addToModItems(new Item(priId:'134', name:'Spruce Wood Stairs', pic:'spruce_wood_stairs'))
				.addToModItems(new Item(priId:'135', name:'Birch Wood Stairs', pic:'birch_wood_stairs'))
				.addToModItems(new Item(priId:'136', name:'Jungle Wood Stairs', pic:'jungle_wood_stairs'))
				.addToModItems(new Item(priId:'137', name:'Command Block', pic:'command_block'))
				.addToModItems(new Item(priId:'138', name:'Beacon', pic:'beacon'))
				.addToModItems(new Item(priId:'139', secId:'0', name:'Cobblestone Wall', pic:'cobblestone_wall'))
				.addToModItems(new Item(priId:'139', secId:'1', name:'Mossy Cobblestone Wall', pic:'mossy_cobblestone_wall'))
				.addToModItems(new Item(priId:'140', name:'Flower Pot', pic:'flower_pot'))
				.addToModItems(new Item(priId:'141', name:'Carrots', pic:'carrots'))
				.addToModItems(new Item(priId:'142', name:'Potatoes', pic:'potatoes'))
				.addToModItems(new Item(priId:'143', name:'Wooden Button', pic:'wooden_button'))
				.addToModItems(new Item(priId:'144', secId:'0', name:'Skeleton Head (Block)', pic:'skeleton_head'))
				.addToModItems(new Item(priId:'144', secId:'1', name:'Wither Skeleton Head (Block)', pic:'wither_skeleton_head'))
				.addToModItems(new Item(priId:'144', secId:'2', name:'Zombie Head (Block)', pic:'zombie_head'))
				.addToModItems(new Item(priId:'144', secId:'3', name:'Steve Head (Block)', pic:'steve_head'))
				.addToModItems(new Item(priId:'144', secId:'4', name:'Creeper Head (Block)', pic:'creeper_head'))
				.addToModItems(new Item(priId:'145', name:'Anvil', pic:'anvil'))
				.addToModItems(new Item(priId:'146', name:'Trapped Chest', pic:'trapped_chest'))
				.addToModItems(new Item(priId:'147', name:'Weighted Pressure Plate (Light)', pic:'weighted_pressure_plate_light'))
				.addToModItems(new Item(priId:'148', name:'Weighted Pressure Plate (Heavy)', pic:'weighted_pressure_plate_heavy'))
				.addToModItems(new Item(priId:'149', name:'Redstone Comparator (inactive)', pic:'redstone_comparator_i'))
				.addToModItems(new Item(priId:'150', name:'Redstone Comparator (active)', pic:'redstone_comparator_a'))
				.addToModItems(new Item(priId:'151', name:'Daylight Sensor', pic:'daylight_sensor'))
				.addToModItems(new Item(priId:'152', name:'Block of Redstone', pic:'block_of_redstone'))
				.addToModItems(new Item(priId:'153', name:'Nether Quartz Ore', pic:'nether_quartz_ore'))
				.addToModItems(new Item(priId:'154', name:'Hopper', pic:'hopper'))
				.addToModItems(new Item(priId:'155', secId:'0', name:'Quartz Block', pic:'quartz_block'))
				.addToModItems(new Item(priId:'155', secId:'1', name:'Chiseled Quartz Block', pic:'chiseled_quartz_block'))
				.addToModItems(new Item(priId:'155', secId:'2', name:'Pillar Quartz Block', pic:'pillar_quartz_block'))
				.addToModItems(new Item(priId:'156', name:'Quartz Stairs', pic:'quartz_stairs'))
				.addToModItems(new Item(priId:'157', name:'Activator Rail', pic:'activator_rail'))
				.addToModItems(new Item(priId:'256', name:'Iron Shovel', pic:'iron_shovel'))
				.addToModItems(new Item(priId:'257', name:'Iron Pickaxe', pic:'iron_pickaxe'))
				.addToModItems(new Item(priId:'258', name:'Iron Axe', pic:'iron_axe'))
				.addToModItems(new Item(priId:'259', name:'Flint and Steel', pic:'flint_and_steel'))
				.addToModItems(new Item(priId:'260', name:'Apple', pic:'apple'))
				.addToModItems(new Item(priId:'261', name:'Bow', pic:'bow'))
				.addToModItems(new Item(priId:'262', name:'Arrow', pic:'arrow'))
				.addToModItems(new Item(priId:'263', secId:'0', name:'Coal', pic:'coal'))
				.addToModItems(new Item(priId:'263', secId:'1', name:'Charcoal', pic:'charcoal'))
				.addToModItems(new Item(priId:'264', name:'Diamond', pic:'diamond'))
				.addToModItems(new Item(priId:'265', name:'Iron Ingot', pic:'iron_ingot'))
				.addToModItems(new Item(priId:'266', name:'Gold Ingot', pic:'gold_ingot'))
				.addToModItems(new Item(priId:'267', name:'Iron Sword', pic:'iron_sword'))
				.addToModItems(new Item(priId:'268', name:'Wooden Sword', pic:'wooden_sword'))
				.addToModItems(new Item(priId:'269', name:'Wooden Shovel', pic:'wooden_shovel'))
				.addToModItems(new Item(priId:'270', name:'Wooden Pickaxe', pic:'wooden_pickaxe'))
				.addToModItems(new Item(priId:'271', name:'Wooden Axe', pic:'wooden_axe'))
				.addToModItems(new Item(priId:'272', name:'Stone Sword', pic:'stone_sword'))
				.addToModItems(new Item(priId:'273', name:'Stone Shovel', pic:'stone_shovel'))
				.addToModItems(new Item(priId:'274', name:'Stone Pickaxe', pic:'stone_pickaxe'))
				.addToModItems(new Item(priId:'275', name:'Stone Axe', pic:'stone_axe'))
				.addToModItems(new Item(priId:'276', name:'Diamond Sword', pic:'diamond_sword'))
				.addToModItems(new Item(priId:'277', name:'Diamond Shovel', pic:'diamond_shovel'))
				.addToModItems(new Item(priId:'278', name:'Diamond Pickaxe', pic:'diamond_pickaxe'))
				.addToModItems(new Item(priId:'279', name:'Diamond Axe', pic:'diamond_axe'))
				.addToModItems(new Item(priId:'280', name:'Stick', pic:'stick'))
				.addToModItems(new Item(priId:'281', name:'Bowl', pic:'bowl'))
				.addToModItems(new Item(priId:'282', name:'Mushroom Stew', pic:'mushroom_stew'))
				.addToModItems(new Item(priId:'283', name:'Golden Sword', pic:'golden_sword'))
				.addToModItems(new Item(priId:'284', name:'Golden Shovel', pic:'golden_shovel'))
				.addToModItems(new Item(priId:'285', name:'Golden Pickaxe', pic:'golden_pickaxe'))
				.addToModItems(new Item(priId:'286', name:'Golden Axe', pic:'golden_axe'))
				.addToModItems(new Item(priId:'287', name:'String', pic:'string'))
				.addToModItems(new Item(priId:'288', name:'Feather', pic:'feather'))
				.addToModItems(new Item(priId:'289', name:'Gunpowder', pic:'gunpowder'))
				.addToModItems(new Item(priId:'290', name:'Wooden Hoe', pic:'wooden_hoe'))
				.addToModItems(new Item(priId:'291', name:'Stone Hoe', pic:'stone_hoe'))
				.addToModItems(new Item(priId:'292', name:'Iron Hoe', pic:'iron_hoe'))
				.addToModItems(new Item(priId:'293', name:'Diamond Hoe', pic:'diamond_hoe'))
				.addToModItems(new Item(priId:'294', name:'Gold Hoe', pic:'gold_hoe'))
				.addToModItems(new Item(priId:'295', name:'Seeds', pic:'seeds'))
				.addToModItems(new Item(priId:'296', name:'Wheat', pic:'wheat'))
				.addToModItems(new Item(priId:'297', name:'Bread', pic:'bread'))
				.addToModItems(new Item(priId:'298', name:'Leather Cap', pic:'leather_cap'))
				.addToModItems(new Item(priId:'299', name:'Leather Tunic', pic:'leather_tunic'))
				.addToModItems(new Item(priId:'300', name:'Leather Pants', pic:'leather_pants'))
				.addToModItems(new Item(priId:'301', name:'Leather Boots', pic:'leather_boots'))
				.addToModItems(new Item(priId:'302', name:'Chain Helmet', pic:'chain_helmet'))
				.addToModItems(new Item(priId:'303', name:'Chain Chestplate', pic:'chain_chestplate'))
				.addToModItems(new Item(priId:'304', name:'Chain Leggings', pic:'chain_leggings'))
				.addToModItems(new Item(priId:'305', name:'Chain Boots', pic:'chain_boots'))
				.addToModItems(new Item(priId:'306', name:'Iron Helmet', pic:'iron_helmet'))
				.addToModItems(new Item(priId:'307', name:'Iron Chestplate', pic:'iron_chestplate'))
				.addToModItems(new Item(priId:'308', name:'Iron Leggings', pic:'iron_leggings'))
				.addToModItems(new Item(priId:'309', name:'Iron Boots', pic:'iron_boots'))
				.addToModItems(new Item(priId:'310', name:'Diamond Helmet', pic:'diamond_helmet'))
				.addToModItems(new Item(priId:'311', name:'Diamond Chestplate', pic:'diamond_chestplate'))
				.addToModItems(new Item(priId:'312', name:'Diamond Leggings', pic:'diamond_leggings'))
				.addToModItems(new Item(priId:'313', name:'Diamond Boots', pic:'diamond_boots'))
				.addToModItems(new Item(priId:'314', name:'Golden Helmet', pic:'golden_helmet'))
				.addToModItems(new Item(priId:'315', name:'Golden Chestplate', pic:'golden_chestplate'))
				.addToModItems(new Item(priId:'316', name:'Golden Leggings', pic:'golden_leggings'))
				.addToModItems(new Item(priId:'317', name:'Golden Boots', pic:'golden_boots'))
				.addToModItems(new Item(priId:'318', name:'Flint', pic:'flint'))
				.addToModItems(new Item(priId:'319', name:'Raw Porkchop', pic:'raw_porkchop'))
				.addToModItems(new Item(priId:'320', name:'Cooked Porkchop', pic:'cooked_porkchop'))
				.addToModItems(new Item(priId:'321', name:'Painting', pic:'painting'))
				.addToModItems(new Item(priId:'323', name:'Sign', pic:'sign'))
				.addToModItems(new Item(priId:'322', secId:'0', name:'Golden Apple', pic:'golden_apple'))
				.addToModItems(new Item(priId:'322', secId:'1', name:'Enchanted Golden Apple', pic:'enchanted_golden_apple'))
				.addToModItems(new Item(priId:'324', name:'Wooden Door', pic:'wooden_door'))
				.addToModItems(new Item(priId:'325', name:'Bucket', pic:'bucket'))
				.addToModItems(new Item(priId:'326', name:'Water Bucket', pic:'water_bucket'))
				.addToModItems(new Item(priId:'327', name:'Lava Bucket', pic:'lava_bucket'))
				.addToModItems(new Item(priId:'328', name:'Minecart', pic:'minecart'))
				.addToModItems(new Item(priId:'329', name:'Saddle', pic:'saddle'))
				.addToModItems(new Item(priId:'330', name:'Iron Door', pic:'iron_door'))
				.addToModItems(new Item(priId:'331', name:'Redstone', pic:'redstone'))
				.addToModItems(new Item(priId:'332', name:'Snowball', pic:'snowball'))
				.addToModItems(new Item(priId:'333', name:'Boat', pic:'boat'))
				.addToModItems(new Item(priId:'334', name:'Leather', pic:'leather'))
				.addToModItems(new Item(priId:'335', name:'Milk', pic:'milk'))
				.addToModItems(new Item(priId:'336', name:'Brick', pic:'brick'))
				.addToModItems(new Item(priId:'337', name:'Clay', pic:'clay'))
				.addToModItems(new Item(priId:'338', name:'Sugar Canes', pic:'sugar_canes'))
				.addToModItems(new Item(priId:'339', name:'Paper', pic:'paper'))
				.addToModItems(new Item(priId:'340', name:'Book', pic:'book'))
				.addToModItems(new Item(priId:'341', name:'Slimeball', pic:'slimeball'))
				.addToModItems(new Item(priId:'342', name:'Minecart with Chest', pic:'minecart_with_chest'))
				.addToModItems(new Item(priId:'343', name:'Minecart with Furnace', pic:'minecart_with_furnace'))
				.addToModItems(new Item(priId:'344', name:'Egg', pic:'egg'))
				.addToModItems(new Item(priId:'345', name:'Compass', pic:'compass'))
				.addToModItems(new Item(priId:'346', name:'Fishing Rod', pic:'fishing_rod'))
				.addToModItems(new Item(priId:'347', name:'Clock', pic:'clock'))
				.addToModItems(new Item(priId:'348', name:'Glowstone Dust', pic:'glowstone_dust'))
				.addToModItems(new Item(priId:'349', name:'Raw Fish', pic:'raw_fish'))
				.addToModItems(new Item(priId:'350', name:'Cooked Fish', pic:'cooked_fish'))
				.addToModItems(new Item(priId:'351', secId:'0', name:'Ink Sack', pic:'ink_sack'))
				.addToModItems(new Item(priId:'351', secId:'1', name:'Rose Red Dye', pic:'rose_red_dye'))
				.addToModItems(new Item(priId:'351', secId:'2', name:'Cactus Green Dye', pic:'cactus_green_dye'))
				.addToModItems(new Item(priId:'351', secId:'3', name:'Cocoa Bean', pic:'cocoa_bean'))
				.addToModItems(new Item(priId:'351', secId:'4', name:'Lapis Lazuli', pic:'lapis_lazuli'))
				.addToModItems(new Item(priId:'351', secId:'5', name:'Purple Dye', pic:'purple_dye'))
				.addToModItems(new Item(priId:'351', secId:'6', name:'Cyan Dye', pic:'cyan_dye'))
				.addToModItems(new Item(priId:'351', secId:'7', name:'Light Gray Dye', pic:'light_gray_dye'))
				.addToModItems(new Item(priId:'351', secId:'8', name:'Gray Dye', pic:'gray_dye'))
				.addToModItems(new Item(priId:'351', secId:'9', name:'Pink Dye', pic:'pink_dye'))
				.addToModItems(new Item(priId:'351', secId:'10', name:'Lime Dye', pic:'lime_dye'))
				.addToModItems(new Item(priId:'351', secId:'11', name:'Dandelion Yellow Dye', pic:'dandelion_yellow_dye'))
				.addToModItems(new Item(priId:'351', secId:'12', name:'Light Blue Dye', pic:'light_blue_dye'))
				.addToModItems(new Item(priId:'351', secId:'13', name:'Magenta Dye', pic:'magenta_dye'))
				.addToModItems(new Item(priId:'351', secId:'14', name:'Orange Dye', pic:'orange_dye'))
				.addToModItems(new Item(priId:'351', secId:'15', name:'Bone Meal', pic:'bone_meal'))
				.addToModItems(new Item(priId:'352', name:'Bone', pic:'bone'))
				.addToModItems(new Item(priId:'353', name:'Sugar', pic:'sugar'))
				.addToModItems(new Item(priId:'354', name:'Cake', pic:'cake'))
				.addToModItems(new Item(priId:'355', name:'Bed', pic:'bed'))
				.addToModItems(new Item(priId:'356', name:'Redstone Repeater', pic:'redstone_repeater'))
				.addToModItems(new Item(priId:'357', name:'Cookie', pic:'cookie'))
				.addToModItems(new Item(priId:'358', name:'Map', pic:'map'))
				.addToModItems(new Item(priId:'359', name:'Shears', pic:'shears'))
				.addToModItems(new Item(priId:'360', name:'Melon', pic:'melon'))
				.addToModItems(new Item(priId:'361', name:'Pumpkin Seeds', pic:'pumpkin_seeds'))
				.addToModItems(new Item(priId:'362', name:'Melon Seeds', pic:'melon_seeds'))
				.addToModItems(new Item(priId:'363', name:'Raw Beef', pic:'raw_beef'))
				.addToModItems(new Item(priId:'364', name:'Steak', pic:'steak'))
				.addToModItems(new Item(priId:'365', name:'Raw Chicken', pic:'raw_chicken'))
				.addToModItems(new Item(priId:'366', name:'Cooked Chicken', pic:'cooked_chicken'))
				.addToModItems(new Item(priId:'367', name:'Rotten Flesh', pic:'rotten_flesh'))
				.addToModItems(new Item(priId:'368', name:'Ender Pearl', pic:'ender_pearl'))
				.addToModItems(new Item(priId:'369', name:'Blaze Rod', pic:'blaze_rod'))
				.addToModItems(new Item(priId:'370', name:'Ghast Tear', pic:'ghast_tear'))
				.addToModItems(new Item(priId:'371', name:'Gold Nugget', pic:'gold_nugget'))
				.addToModItems(new Item(priId:'372', name:'Nether Wart', pic:'nether_wart'))
				.addToModItems(new Item(priId:'373', name:'Water Bottle', pic:'water_bottle'))
				.addToModItems(new Item(priId:'373', secId:'16', name:'Awkward Potion', pic:'awkward_potion'))
				.addToModItems(new Item(priId:'373', secId:'32', name:'Thick Potion', pic:'thick_potion'))
				.addToModItems(new Item(priId:'373', secId:'64', name:'Mundane Potion', pic:'mundane_potion'))
				.addToModItems(new Item(priId:'373', secId:'8193', name:'Regeneration Potion (0:45)', pic:'regeneration_potion_045'))
				.addToModItems(new Item(priId:'373', secId:'8194', name:'Swiftness Potion (3:00)', pic:'swiftness_potion_300'))
				.addToModItems(new Item(priId:'373', secId:'8195', name:'Fire Resistance Potion (3:00)', pic:'fire_resistance_potion_300'))
				.addToModItems(new Item(priId:'373', secId:'8196', name:'Poison Potion (0:45)', pic:'poison_potion_045'))
				.addToModItems(new Item(priId:'373', secId:'8197', name:'Healing Potion', pic:'healing_potion'))
				.addToModItems(new Item(priId:'373', secId:'8198', name:'Night Vision Potion (3:00)', pic:'night_vision_potion_300'))
				.addToModItems(new Item(priId:'373', secId:'8200', name:'Weakness Potion (1:30)', pic:'weakness_potion_130'))
				.addToModItems(new Item(priId:'373', secId:'8201', name:'Strength Potion (3:00)', pic:'strength_potion_300'))
				.addToModItems(new Item(priId:'373', secId:'8202', name:'Slowness Potion (1:30)', pic:'slowness_potion_130'))
				.addToModItems(new Item(priId:'373', secId:'8204', name:'Harming Potion', pic:'harming_potion'))
				.addToModItems(new Item(priId:'373', secId:'8206', name:'Invisibility Potion (3:00)', pic:'invisibility_potion_300'))
				.addToModItems(new Item(priId:'373', secId:'8225', name:'Regeneration Potion II (0:22)', pic:'regeneration_potion_ii_022'))
				.addToModItems(new Item(priId:'373', secId:'8226', name:'Swiftness Potion II (1:30)', pic:'swiftness_potion_ii_130'))
				.addToModItems(new Item(priId:'373', secId:'8228', name:'Poison Potion II (0:22)', pic:'poison_potion_ii_022'))
				.addToModItems(new Item(priId:'373', secId:'8229', name:'Healing Potion II', pic:'healing_potion_ii'))
				.addToModItems(new Item(priId:'373', secId:'8233', name:'Strength Potion II (1:30)', pic:'strength_potion_ii_130'))
				.addToModItems(new Item(priId:'373', secId:'8236', name:'Harming Potion II', pic:'harming_potion_ii'))
				.addToModItems(new Item(priId:'373', secId:'8257', name:'Regeneration Potion (2:00)', pic:'regeneration_potion_200'))
				.addToModItems(new Item(priId:'373', secId:'8258', name:'Swiftness Potion (8:00)', pic:'swiftness_potion_800'))
				.addToModItems(new Item(priId:'373', secId:'8259', name:'Fire Resistance Potion (8:00)', pic:'fire_resistance_potion_800'))
				.addToModItems(new Item(priId:'373', secId:'8260', name:'Poison Potion (2:00)', pic:'poison_potion_200'))
				.addToModItems(new Item(priId:'373', secId:'8262', name:'Night Vision Potion (8:00)', pic:'night_vision_potion_800'))
				.addToModItems(new Item(priId:'373', secId:'8264', name:'Weakness Potion (4:00)', pic:'weakness_potion_400'))
				.addToModItems(new Item(priId:'373', secId:'8265', name:'Strength Potion (8:00)', pic:'strength_potion_800'))
				.addToModItems(new Item(priId:'373', secId:'8266', name:'Slowness Potion (4:00)', pic:'slowness_potion_400'))
				.addToModItems(new Item(priId:'373', secId:'8270', name:'Invisibility Potion (8:00)', pic:'invisibility_potion_800'))
				.addToModItems(new Item(priId:'373', secId:'16385', name:'Regeneration Splash (0:33)', pic:'regeneration_splash_033'))
				.addToModItems(new Item(priId:'373', secId:'16386', name:'Swiftness Splash (2:15)', pic:'swiftness_splash_215'))
				.addToModItems(new Item(priId:'373', secId:'16387', name:'Fire Resistance Splash (2:15)', pic:'fire_resistance_splash_215'))
				.addToModItems(new Item(priId:'373', secId:'16388', name:'Poison Splash (0:33)', pic:'poison_splash_033'))
				.addToModItems(new Item(priId:'373', secId:'16389', name:'Healing Splash', pic:'healing_splash'))
				.addToModItems(new Item(priId:'373', secId:'16390', name:'Night Vision Splash (2:15)', pic:'night_vision_splash_215'))
				.addToModItems(new Item(priId:'373', secId:'16392', name:'Weakness Splash (1:07)', pic:'weakness_splash_107'))
				.addToModItems(new Item(priId:'373', secId:'16393', name:'Strength Splash (2:15)', pic:'strength_splash_215'))
				.addToModItems(new Item(priId:'373', secId:'16394', name:'Slowness Splash (1:07)', pic:'slowness_splash_107'))
				.addToModItems(new Item(priId:'373', secId:'16396', name:'Harming Splash', pic:'harming_splash'))
				.addToModItems(new Item(priId:'373', secId:'16398', name:'Invisibility Splash (2:15)', pic:'invisibility_splash_215'))
				.addToModItems(new Item(priId:'373', secId:'16417', name:'Regeneration Splash II (0:16)', pic:'regeneration_splash_ii_016'))
				.addToModItems(new Item(priId:'373', secId:'16418', name:'Swiftness Splash II (1:07)', pic:'swiftness_splash_ii_107'))
				.addToModItems(new Item(priId:'373', secId:'16420', name:'Poison Splash II (0:16)', pic:'poison_splash_ii_016'))
				.addToModItems(new Item(priId:'373', secId:'16421', name:'Healing Splash II', pic:'healing_splash_ii'))
				.addToModItems(new Item(priId:'373', secId:'16425', name:'Strength Splash II (1:07)', pic:'strength_splash_ii_107'))
				.addToModItems(new Item(priId:'373', secId:'16428', name:'Harming Splash II', pic:'harming_splash_ii'))
				.addToModItems(new Item(priId:'373', secId:'16449', name:'Regeneration Splash (1:30)', pic:'regeneration_splash_130'))
				.addToModItems(new Item(priId:'373', secId:'16450', name:'Swiftness Splash (6:00)', pic:'swiftness_splash_600'))
				.addToModItems(new Item(priId:'373', secId:'16451', name:'Fire Resistance Splash (6:00)', pic:'fire_resistance_splash_600'))
				.addToModItems(new Item(priId:'373', secId:'16452', name:'Poison Splash (1:30)', pic:'poison_splash_130'))
				.addToModItems(new Item(priId:'373', secId:'16454', name:'Night Vision Splash (6:00)', pic:'night_vision_splash_600'))
				.addToModItems(new Item(priId:'373', secId:'16456', name:'Weakness Splash (3:00)', pic:'weakness_splash_300'))
				.addToModItems(new Item(priId:'373', secId:'16457', name:'Strength Splash (6:00)', pic:'strength_splash_600'))
				.addToModItems(new Item(priId:'373', secId:'16458', name:'Slowness Splash (3:00)', pic:'slowness_splash_300'))
				.addToModItems(new Item(priId:'373', secId:'16462', name:'Invisibility Splash (6:00)', pic:'invisibility_Splash_600'))
				.addToModItems(new Item(priId:'374', name:'Glass Bottle', pic:'glass_bottle'))
				.addToModItems(new Item(priId:'375', name:'Spider Eye', pic:'spider_eye'))
				.addToModItems(new Item(priId:'376', name:'Fermented Spider Eye', pic:'fermented_spider_eye'))
				.addToModItems(new Item(priId:'377', name:'Blaze Powder', pic:'blaze_powder'))
				.addToModItems(new Item(priId:'378', name:'Magma Cream', pic:'magma_cream'))
				.addToModItems(new Item(priId:'379', name:'Brewing Stand', pic:'brewing_stand_item'))
				.addToModItems(new Item(priId:'380', name:'Cauldron', pic:'cauldron_item'))
				.addToModItems(new Item(priId:'381', name:'Eye of Ender', pic:'eye_of_ender'))
				.addToModItems(new Item(priId:'382', name:'Glistering Melon', pic:'glistering_melon'))
				.addToModItems(new Item(priId:'383', secId:'50', name:'Spawn Egg (Creeper)', pic:'spawn_egg_creeper'))
				.addToModItems(new Item(priId:'383', secId:'51', name:'Spawn Egg (Skeleton)', pic:'spawn_egg_skeleton'))
				.addToModItems(new Item(priId:'383', secId:'52', name:'Spawn Egg (Spider)', pic:'spawn_egg_spider'))
				.addToModItems(new Item(priId:'383', secId:'54', name:'Spawn Egg (Zombie)', pic:'spawn_egg_zombie'))
				.addToModItems(new Item(priId:'383', secId:'55', name:'Spawn Egg (Slime)', pic:'spawn_egg_slime'))
				.addToModItems(new Item(priId:'383', secId:'56', name:'Spawn Egg (Ghast)', pic:'spawn_egg_ghast'))
				.addToModItems(new Item(priId:'383', secId:'57', name:'Spawn Egg (Zombie Pigmen)', pic:'spawn_egg_zombie_pigmen'))
				.addToModItems(new Item(priId:'383', secId:'58', name:'Spawn Egg (Enderman)', pic:'spawn_egg_enderman'))
				.addToModItems(new Item(priId:'383', secId:'59', name:'Spawn Egg (Cave Spider)', pic:'spawn_egg_cave_spider'))
				.addToModItems(new Item(priId:'383', secId:'60', name:'Spawn Egg (Silverfish)', pic:'spawn_egg_silverfish'))
				.addToModItems(new Item(priId:'383', secId:'61', name:'Spawn Egg (Blaze)', pic:'spawn_egg_blaze'))
				.addToModItems(new Item(priId:'383', secId:'62', name:'Spawn Egg (Magma Cube)', pic:'spawn_egg_magma_cube'))
				.addToModItems(new Item(priId:'383', secId:'65', name:'Spawn Egg (Bat)', pic:'spawn_egg_bat'))
				.addToModItems(new Item(priId:'383', secId:'66', name:'Spawn Egg (Witch)', pic:'spawn_egg_witch'))
				.addToModItems(new Item(priId:'383', secId:'90', name:'Spawn Egg (Pig)', pic:'spawn_egg_pig'))
				.addToModItems(new Item(priId:'383', secId:'91', name:'Spawn Egg (Sheep)', pic:'spawn_egg_sheep'))
				.addToModItems(new Item(priId:'383', secId:'92', name:'Spawn Egg (Cow)', pic:'spawn_egg_cow'))
				.addToModItems(new Item(priId:'383', secId:'93', name:'Spawn Egg (Chicken)', pic:'spawn_egg_chicken'))
				.addToModItems(new Item(priId:'383', secId:'94', name:'Spawn Egg (Squid)', pic:'spawn_egg_squid'))
				.addToModItems(new Item(priId:'383', secId:'95', name:'Spawn Egg (Wolf)', pic:'spawn_egg_wolf'))
				.addToModItems(new Item(priId:'383', secId:'96', name:'Spawn Egg (Mooshroom)', pic:'spawn_egg_mooshroom'))
				.addToModItems(new Item(priId:'383', secId:'98', name:'Spawn Egg (Ocelot)', pic:'spawn_egg_ocelot'))
				.addToModItems(new Item(priId:'383', secId:'120', name:'Spawn Egg (Villager)', pic:'spawn_egg_villager'))
				.addToModItems(new Item(priId:'384', name:'Bottle o\' Enchanting', pic:'bottle_o_enchanting'))
				.addToModItems(new Item(priId:'385', name:'Fire Charge', pic:'fire_charge'))
				.addToModItems(new Item(priId:'386', name:'Book and Quill', pic:'book_and_quill'))
				.addToModItems(new Item(priId:'387', name:'Written Book', pic:'written_book'))
				.addToModItems(new Item(priId:'388', name:'Emerald', pic:'emerald'))
				.addToModItems(new Item(priId:'389', name:'Item Frame', pic:'item_frame'))
				.addToModItems(new Item(priId:'390', name:'Flower Pot', pic:'flower_pot_item'))
				.addToModItems(new Item(priId:'391', name:'Carrot', pic:'carrot'))
				.addToModItems(new Item(priId:'392', name:'Potato', pic:'potato'))
				.addToModItems(new Item(priId:'393', name:'Baked Potato', pic:'baked_potato'))
				.addToModItems(new Item(priId:'394', name:'Poisonous Potato', pic:'poisonous_potato'))
				.addToModItems(new Item(priId:'395', name:'Empty Map', pic:'empty_map'))
				.addToModItems(new Item(priId:'396', name:'Golden Carrot', pic:'golden_carrot'))
				.addToModItems(new Item(priId:'397', secId:'0', name:'Head (Skeleton)', pic:'head_skeleton'))
				.addToModItems(new Item(priId:'397', secId:'1', name:'Head (Wither Skeleton)', pic:'head_wither_skeleton'))
				.addToModItems(new Item(priId:'397', secId:'2', name:'Head (Zombie)', pic:'head_zombie'))
				.addToModItems(new Item(priId:'397', secId:'3', name:'Head (Steve)', pic:'head_steve'))
				.addToModItems(new Item(priId:'397', secId:'4', name:'Head (Creeper)', pic:'head_creeper'))
				.addToModItems(new Item(priId:'398', name:'Carrot on a Stick', pic:'carrot_on_a_stick'))
				.addToModItems(new Item(priId:'399', name:'Nether Star', pic:'nether_star'))
				.addToModItems(new Item(priId:'400', name:'Pumpkin Pie', pic:'pumpkin_pie'))
				.addToModItems(new Item(priId:'401', name:'Firework Rocket', pic:'firework_rocket'))
				.addToModItems(new Item(priId:'402', name:'Firework Star', pic:'firework_star'))
				.addToModItems(new Item(priId:'403', name:'Enchanted Book', pic:'enchanted_book'))
				.addToModItems(new Item(priId:'404', name:'Redstone Comparator', pic:'redstone_comparator'))
				.addToModItems(new Item(priId:'405', name:'Nether Brick', pic:'nether_brick'))
				.addToModItems(new Item(priId:'406', name:'Nether Quartz', pic:'nether_quartz'))
				.addToModItems(new Item(priId:'407', name:'Minecart with TNT', pic:'minecart_with_tnt'))
				.addToModItems(new Item(priId:'2256', name:'13 Disc', pic:'disc_13'))
				.addToModItems(new Item(priId:'2257', name:'Cat Disc', pic:'cat_disc'))
				.addToModItems(new Item(priId:'2258', name:'blocks Disc', pic:'blocks_disc'))
				.addToModItems(new Item(priId:'2259', name:'chirp Disc', pic:'chirp_disc'))
				.addToModItems(new Item(priId:'2260', name:'far Disc', pic:'far_disc'))
				.addToModItems(new Item(priId:'2261', name:'mall Disc', pic:'mall_disc'))
				.addToModItems(new Item(priId:'2262', name:'mellohi Disc', pic:'mellohi_disc'))
				.addToModItems(new Item(priId:'2263', name:'stal Disc', pic:'stal_disc'))
				.addToModItems(new Item(priId:'2264', name:'strad Disc', pic:'strad_disc'))
				.addToModItems(new Item(priId:'2265', name:'ward Disc', pic:'ward_disc'))
				.addToModItems(new Item(priId:'2266', name:'11 Disc', pic:'disc_11'))
				.addToModItems(new Item(priId:'2267', name:'wait Disc', pic:'wait_disc')))
			.save(flush:true)
	}
}
